export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_ERROR = 'GET_USERS_LIST_ERROR';

export const CREATE_USER_ITEM = 'CREATE_USER_ITEM';
export const CREATE_USER_ITEM_SUCCESS = 'CREATE_USER_ITEM_SUCCESS';
export const CREATE_USER_ITEM_ERROR = 'CREATE_USER_ITEM_ERROR';

export const GET_USER_ITEM = 'GET_USER_ITEM';
export const GET_USER_ITEM_SUCCESS = 'GET_USER_ITEM_SUCCESS';
export const GET_USER_ITEM_ERROR = 'GET_USER_ITEM_ERROR';

export const UPDATE_USER_ITEM = 'UPDATE_USER_ITEM';
export const UPDATE_USER_ITEM_SUCCESS = 'UPDATE_USER_ITEM_SUCCESS';
export const UPDATE_USER_ITEM_ERROR = 'UPDATE_USER_ITEM_ERROR';

export const DELETE_USER_ITEM = 'DELETE_USER_ITEM';
export const DELETE_USER_ITEM_SUCCESS = 'DELETE_USER_ITEM_SUCCESS';
export const DELETE_USER_ITEM_ERROR = 'DELETE_USER_ITEM_ERROR';

export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const INCREMENT_PAGE_SUCCESS = 'INCREMENT_PAGE_SUCCESS';
export const DECREMENT_PAGE = 'DECREMENT_PAGE';
export const DECREMENT_PAGE_SUCCESS = 'DECREMENT_PAGE_SUCCESS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';
